# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("MumbleServer")

# Modules:
try:
    from .. import MumbleServer_ice
except Exception:
    import MumbleServer_ice

# Submodules:
