"""Canonical entity type constants shared by FG and BG."""

ENTITY_TYPE_ALLIANCE = 'alliance'
ENTITY_TYPE_CORPORATION = 'corporation'
ENTITY_TYPE_PILOT = 'pilot'

VALID_ENTITY_TYPES = {ENTITY_TYPE_ALLIANCE, ENTITY_TYPE_CORPORATION, ENTITY_TYPE_PILOT}

CATEGORY_ALLIANCE = 'alliance'
CATEGORY_CORPORATION = 'corporation'
CATEGORY_CHARACTER = 'character'

VALID_CATEGORIES = {CATEGORY_ALLIANCE, CATEGORY_CORPORATION, CATEGORY_CHARACTER}

TYPE_TO_CATEGORY = {
    ENTITY_TYPE_ALLIANCE: CATEGORY_ALLIANCE,
    ENTITY_TYPE_CORPORATION: CATEGORY_CORPORATION,
    ENTITY_TYPE_PILOT: CATEGORY_CHARACTER,
}

CATEGORY_TO_TYPE = {
    CATEGORY_ALLIANCE: ENTITY_TYPE_ALLIANCE,
    CATEGORY_CORPORATION: ENTITY_TYPE_CORPORATION,
    CATEGORY_CHARACTER: ENTITY_TYPE_PILOT,
}
