# Generated by Django 4.2.29 on 2026-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.BigIntegerField(help_text='EVE Online ID (alliance, corporation, or character).', unique=True)),
                ('entity_type', models.CharField(choices=[('alliance', 'Alliance'), ('corporation', 'Corporation'), ('pilot', 'Pilot')], help_text='Deducible from ID range but kept for query convenience.', max_length=16)),
                ('deny', models.BooleanField(default=False, help_text='Off = permit (default). On = deny access.')),
                ('note', models.TextField(blank=True, default='', help_text='Admin notes (e.g. reason for denial, ticket reference).')),
                ('created_by', models.CharField(blank=True, default='', help_text='Who added this rule.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'access control entry',
                'verbose_name_plural': 'access control list',
                'db_table': 'fg_access_rule',
                'ordering': ['entity_type', 'entity_id'],
            },
        ),
        migrations.CreateModel(
            name='AccessRuleAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl_id', models.IntegerField(blank=True, help_text='ACL primary key at the time of the audit event.', null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('sync', 'Sync')], max_length=16)),
                ('actor_username', models.CharField(blank=True, default='', help_text='Username that initiated the change.', max_length=255)),
                ('source', models.CharField(blank=True, default='', help_text='Originating FG surface (e.g. ACL UI or admin).', max_length=64)),
                ('entity_id', models.BigIntegerField(blank=True, help_text='EVE Online ID (alliance, corporation, or character) when tied to one ACL row.', null=True)),
                ('entity_type', models.CharField(blank=True, choices=[('alliance', 'Alliance'), ('corporation', 'Corporation'), ('pilot', 'Pilot')], max_length=16, null=True)),
                ('deny', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('acl_created_by', models.CharField(blank=True, default='', help_text='Original creator recorded on the active ACL row.', max_length=255)),
                ('previous', models.JSONField(blank=True, default=dict, help_text='Prior ACL row snapshot for update events.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event context such as sync trigger and BG response summary.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'access control audit entry',
                'verbose_name_plural': 'access control audit log',
                'db_table': 'fg_access_rule_audit',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
