# Generated by Django 4.2.29 on 2026-03-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumble_fg', '0000_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='acl_admin',
            field=models.BooleanField(
                default=False,
                help_text='Pilot-only Murmur admin marker. Ignored for alliance/corporation rules.',
            ),
        ),
        migrations.AlterModelOptions(
            name='accessrule',
            options={
                'db_table': 'fg_access_rule',
                'ordering': ['entity_type', 'entity_id'],
                'permissions': [
                    ('manage_acl_admin', 'Can set or clear ACL pilot admin markers'),
                    ('view_acl_admin_my_corp', 'Can view ACL pilot admin markers in own corporation'),
                    ('view_acl_admin_my_alliance', 'Can view ACL pilot admin markers in own alliance'),
                    ('view_acl_admin_all', 'Can view ACL pilot admin markers for all pilots'),
                ],
                'verbose_name': 'access control entry',
                'verbose_name_plural': 'access control list',
            },
        ),
        migrations.CreateModel(
            name='PilotSnapshotHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkid', models.BigIntegerField(help_text='Stable FG/BG account identity key.', unique=True)),
                (
                    'pilot_data_hash',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        help_text='Hash of pilot snapshot payload for this account (md5 placeholder).',
                        max_length=64,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fg_pilot_snapshot_hash',
                'ordering': ['pkid'],
                'verbose_name': 'pilot snapshot hash',
                'verbose_name_plural': 'pilot snapshot hashes',
            },
        ),
        migrations.AddConstraint(
            model_name='accessrule',
            constraint=models.CheckConstraint(
                check=models.Q(('acl_admin', False), ('entity_type', 'pilot'), _connector='OR'),
                name='fg_access_rule_acl_admin_pilot_only',
            ),
        ),
    ]
