# Generated by Django 4.2.29 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg', '0000_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotSnapshotHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkid', models.BigIntegerField(help_text='Stable FG/BG account identity key.', unique=True)),
                ('pilot_data_hash', models.CharField(blank=True, db_index=True, default='', help_text='Hash of pilot snapshot payload for this account (md5 placeholder).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pilot snapshot hash',
                'verbose_name_plural': 'pilot snapshot hashes',
                'db_table': 'fg_pilot_snapshot_hash',
                'ordering': ['pkid'],
            },
        ),
    ]
