# Generated by Django 4.2.29 on 2026-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumble_fg', '0001_access_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrule',
            options={'ordering': ['entity_type', 'entity_id'], 'verbose_name': 'access control entry', 'verbose_name_plural': 'access control list'},
        ),
        migrations.RenameField(
            model_name='accessrule',
            old_name='block',
            new_name='deny',
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='deny',
            field=models.BooleanField(default=False, help_text='Off = permit (default). On = deny access.'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Admin notes (e.g. reason for denial, ticket reference).'),
        ),
    ]
